log_path: "log/"
data_path: "data/"
binance_coin:
  api_key: ""
  api_secret: ""
  rest_url: ""
  websocket_url: ""
binance_spot:
  api_key: ""
  api_secret: ""
  rest_url: ""
  websocket_url: ""
binance_stable:
  api_key: ""
  api_secret: ""
  rest_url: ""
  websocket_url: ""
bitmex:
  api_key: ""
  api_secret: ""
  rest_url: ""
  websocket_url: ""
bitstamp:
  api_key: ""
  api_secret: ""
  rest_url: ""
  websocket_url: ""
coinbase:
  api_key: ""
  api_secret: ""
  rest_url: ""
  websocket_url: ""
deribit:
  api_key: ""
  api_secret: ""
  rest_url: ""
  websocket_url: ""
ftx:
  api_key: ""
  api_secret: ""
  rest_url: ""
  websocket_url: ""
kraken_futures:
  api_key: ""
  api_secret: ""
  rest_url: ""
  websocket_url: ""
kraken:
  api_key: ""
  api_secret: ""
  rest_url: ""
  websocket_url: ""
okx:
  api_key: ""
  api_secret: ""
  rest_url: ""
  websocket_url: ""