log_path: "log/"
data_path: "data/"
data_quotes_path: "data/quotes/"
data_trades_path: "data/trades/"
binance_coin:
  api_key: ""
  api_secret: ""
  rest_url: ""
  websocket_url: "wss://dstream.binance.com/ws/"
binance_spot:
  api_key: ""
  api_secret: ""
  rest_url: ""
  websocket_url: "wss://stream.binance.com/stream/"
binance_stable:
  api_key: ""
  api_secret: ""
  rest_url: ""
  websocket_url: "wss://fstream.binance.com/ws/"
bitmex:
  api_key: ""
  api_secret: ""
  rest_url: ""
  websocket_url: "wss://www.bitmex.com/realtime/"
bitstamp:
  api_key: ""
  api_secret: ""
  rest_url: ""
  websocket_url: "wss://ws.bitstamp.net/"
coinbase:
  api_key: ""
  api_secret: ""
  rest_url: ""
  websocket_url: "wss://ws-feed-public.sandbox.pro.coinbase.com/"
deribit:
  api_key: ""
  api_secret: ""
  rest_url: ""
  websocket_url: "wss://www.deribit.com/ws/api/v2/"
ftx:
  api_key: ""
  api_secret: ""
  rest_url: ""
  websocket_url: "wss://ftx.com/ws/"
kraken_futures:
  api_key: ""
  api_secret: ""
  rest_url: ""
  websocket_url: "wss://futures.kraken.com/ws/v1/"
kraken:
  api_key: ""
  api_secret: ""
  rest_url: ""
  websocket_url: "wss://ws.kraken.com/"
okx:
  api_key: ""
  api_secret: ""
  rest_url: ""
  websocket_url: "wss://ws.okx.com:8443/ws/v5/public/"